logging:
  file: app.log
  level:
    '*': DEBUG
  register-shutdown-hook: true
server:
  servlet:
    context-path: /api
  port: 8084
spring:
  datasource:
    initialization-mode: never
    url: jdbc:h2:file:~/my_expenses
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: false
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
spring-datasource:
  platform: H2
